infos:
    name: ZINGUERIE PROVENCALE
    address: 110 rue de la Tuilerie  
    zipcode: "13290"
    city: AIX EN PROVENCE
    phone: 06 69 69 55 56
    email: zinguerieprovencale@orange.fr
    keywords: 
pages:
    index.html:
        title: Accueil
        description:  
    mentions-legales.html:
        title: Mentions Légales
        description: Mentions Légales - ZINGUERIE PROVENCALE
    plan.html:
        title: Plan du site
        description: Plan du site - ZINGUERIE PROVENCALE